#release configuration for hotfix branches
plugins:
  - path: "@semantic-release/commit-analyzer"
    preset: conventionalcommits

  - path: "@semantic-release/release-notes-generator"
    preset: conventionalcommits

  - path: "@semantic-release/github"

  - path: "@semantic-release/exec"

branches:
  - main
  - name: develop
    prerelease: beta
  - name: hotfix/*
    prerelease: false
    channel: false
