// Code generated by MockGen. DO NOT EDIT.
// Source: metadata_indexes.go
//
// Generated by this command:
//
//	mockgen -source=metadata_indexes.go -destination=mocks/mock_metadata_indexes.go -package=mocks MetadataIndexesService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v4/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataIndexesService is a mock of MetadataIndexesService interface.
type MockMetadataIndexesService struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataIndexesServiceMockRecorder
	isgomock struct{}
}

// MockMetadataIndexesServiceMockRecorder is the mock recorder for MockMetadataIndexesService.
type MockMetadataIndexesServiceMockRecorder struct {
	mock *MockMetadataIndexesService
}

// NewMockMetadataIndexesService creates a new mock instance.
func NewMockMetadataIndexesService(ctrl *gomock.Controller) *MockMetadataIndexesService {
	mock := &MockMetadataIndexesService{ctrl: ctrl}
	mock.recorder = &MockMetadataIndexesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataIndexesService) EXPECT() *MockMetadataIndexesServiceMockRecorder {
	return m.recorder
}

// CreateMetadataIndex mocks base method.
func (m *MockMetadataIndexesService) CreateMetadataIndex(ctx context.Context, entityName string, input *models.CreateMetadataIndexInput) (*models.MetadataIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetadataIndex", ctx, entityName, input)
	ret0, _ := ret[0].(*models.MetadataIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMetadataIndex indicates an expected call of CreateMetadataIndex.
func (mr *MockMetadataIndexesServiceMockRecorder) CreateMetadataIndex(ctx, entityName, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetadataIndex", reflect.TypeOf((*MockMetadataIndexesService)(nil).CreateMetadataIndex), ctx, entityName, input)
}

// DeleteMetadataIndex mocks base method.
func (m *MockMetadataIndexesService) DeleteMetadataIndex(ctx context.Context, entityName, metadataKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMetadataIndex", ctx, entityName, metadataKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMetadataIndex indicates an expected call of DeleteMetadataIndex.
func (mr *MockMetadataIndexesServiceMockRecorder) DeleteMetadataIndex(ctx, entityName, metadataKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMetadataIndex", reflect.TypeOf((*MockMetadataIndexesService)(nil).DeleteMetadataIndex), ctx, entityName, metadataKey)
}

// ListMetadataIndexes mocks base method.
func (m *MockMetadataIndexesService) ListMetadataIndexes(ctx context.Context, entityName string) ([]models.MetadataIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetadataIndexes", ctx, entityName)
	ret0, _ := ret[0].([]models.MetadataIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMetadataIndexes indicates an expected call of ListMetadataIndexes.
func (mr *MockMetadataIndexesServiceMockRecorder) ListMetadataIndexes(ctx, entityName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetadataIndexes", reflect.TypeOf((*MockMetadataIndexesService)(nil).ListMetadataIndexes), ctx, entityName)
}
