// Code generated by MockGen. DO NOT EDIT.
// Source: accounts.go
//
// Generated by this command:
//
//	mockgen -source=accounts.go -destination=mocks/mock_accounts.go -package=mocks AccountsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v4/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountsService is a mock of AccountsService interface.
type MockAccountsService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountsServiceMockRecorder
	isgomock struct{}
}

// MockAccountsServiceMockRecorder is the mock recorder for MockAccountsService.
type MockAccountsServiceMockRecorder struct {
	mock *MockAccountsService
}

// NewMockAccountsService creates a new mock instance.
func NewMockAccountsService(ctrl *gomock.Controller) *MockAccountsService {
	mock := &MockAccountsService{ctrl: ctrl}
	mock.recorder = &MockAccountsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountsService) EXPECT() *MockAccountsServiceMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockAccountsService) CreateAccount(ctx context.Context, organizationID, ledgerID string, input *models.CreateAccountInput) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, organizationID, ledgerID, input)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountsServiceMockRecorder) CreateAccount(ctx, organizationID, ledgerID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountsService)(nil).CreateAccount), ctx, organizationID, ledgerID, input)
}

// DeleteAccount mocks base method.
func (m *MockAccountsService) DeleteAccount(ctx context.Context, organizationID, ledgerID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, organizationID, ledgerID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockAccountsServiceMockRecorder) DeleteAccount(ctx, organizationID, ledgerID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockAccountsService)(nil).DeleteAccount), ctx, organizationID, ledgerID, id)
}

// GetAccount mocks base method.
func (m *MockAccountsService) GetAccount(ctx context.Context, organizationID, ledgerID, id string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, organizationID, ledgerID, id)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockAccountsServiceMockRecorder) GetAccount(ctx, organizationID, ledgerID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockAccountsService)(nil).GetAccount), ctx, organizationID, ledgerID, id)
}

// GetAccountByAlias mocks base method.
func (m *MockAccountsService) GetAccountByAlias(ctx context.Context, organizationID, ledgerID, alias string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByAlias", ctx, organizationID, ledgerID, alias)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByAlias indicates an expected call of GetAccountByAlias.
func (mr *MockAccountsServiceMockRecorder) GetAccountByAlias(ctx, organizationID, ledgerID, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByAlias", reflect.TypeOf((*MockAccountsService)(nil).GetAccountByAlias), ctx, organizationID, ledgerID, alias)
}

// GetAccountByAliasPath mocks base method.
func (m *MockAccountsService) GetAccountByAliasPath(ctx context.Context, organizationID, ledgerID, alias string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByAliasPath", ctx, organizationID, ledgerID, alias)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByAliasPath indicates an expected call of GetAccountByAliasPath.
func (mr *MockAccountsServiceMockRecorder) GetAccountByAliasPath(ctx, organizationID, ledgerID, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByAliasPath", reflect.TypeOf((*MockAccountsService)(nil).GetAccountByAliasPath), ctx, organizationID, ledgerID, alias)
}

// GetAccountsMetricsCount mocks base method.
func (m *MockAccountsService) GetAccountsMetricsCount(ctx context.Context, organizationID, ledgerID string) (*models.MetricsCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsMetricsCount", ctx, organizationID, ledgerID)
	ret0, _ := ret[0].(*models.MetricsCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsMetricsCount indicates an expected call of GetAccountsMetricsCount.
func (mr *MockAccountsServiceMockRecorder) GetAccountsMetricsCount(ctx, organizationID, ledgerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsMetricsCount", reflect.TypeOf((*MockAccountsService)(nil).GetAccountsMetricsCount), ctx, organizationID, ledgerID)
}

// GetBalance mocks base method.
func (m *MockAccountsService) GetBalance(ctx context.Context, organizationID, ledgerID, accountID string) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, organizationID, ledgerID, accountID)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockAccountsServiceMockRecorder) GetBalance(ctx, organizationID, ledgerID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockAccountsService)(nil).GetBalance), ctx, organizationID, ledgerID, accountID)
}

// GetExternalAccount mocks base method.
func (m *MockAccountsService) GetExternalAccount(ctx context.Context, organizationID, ledgerID, assetCode string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalAccount", ctx, organizationID, ledgerID, assetCode)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalAccount indicates an expected call of GetExternalAccount.
func (mr *MockAccountsServiceMockRecorder) GetExternalAccount(ctx, organizationID, ledgerID, assetCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalAccount", reflect.TypeOf((*MockAccountsService)(nil).GetExternalAccount), ctx, organizationID, ledgerID, assetCode)
}

// GetExternalAccountBalance mocks base method.
func (m *MockAccountsService) GetExternalAccountBalance(ctx context.Context, organizationID, ledgerID, assetCode string) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalAccountBalance", ctx, organizationID, ledgerID, assetCode)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalAccountBalance indicates an expected call of GetExternalAccountBalance.
func (mr *MockAccountsServiceMockRecorder) GetExternalAccountBalance(ctx, organizationID, ledgerID, assetCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalAccountBalance", reflect.TypeOf((*MockAccountsService)(nil).GetExternalAccountBalance), ctx, organizationID, ledgerID, assetCode)
}

// ListAccounts mocks base method.
func (m *MockAccountsService) ListAccounts(ctx context.Context, organizationID, ledgerID string, opts models.AccountsListOpts) (*models.ListResponse[models.Account], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Account])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockAccountsServiceMockRecorder) ListAccounts(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockAccountsService)(nil).ListAccounts), ctx, organizationID, ledgerID, opts)
}

// ListAccountsAll mocks base method.
func (m *MockAccountsService) ListAccountsAll(ctx context.Context, organizationID, ledgerID string, opts models.AccountsListOpts) iter.Seq2[models.Account, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountsAll", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Account, error])
	return ret0
}

// ListAccountsAll indicates an expected call of ListAccountsAll.
func (mr *MockAccountsServiceMockRecorder) ListAccountsAll(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountsAll", reflect.TypeOf((*MockAccountsService)(nil).ListAccountsAll), ctx, organizationID, ledgerID, opts)
}

// ListAccountsPages mocks base method.
func (m *MockAccountsService) ListAccountsPages(ctx context.Context, organizationID, ledgerID string, opts models.AccountsListOpts) iter.Seq2[*models.ListResponse[models.Account], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountsPages", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Account], error])
	return ret0
}

// ListAccountsPages indicates an expected call of ListAccountsPages.
func (mr *MockAccountsServiceMockRecorder) ListAccountsPages(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountsPages", reflect.TypeOf((*MockAccountsService)(nil).ListAccountsPages), ctx, organizationID, ledgerID, opts)
}

// UpdateAccount mocks base method.
func (m *MockAccountsService) UpdateAccount(ctx context.Context, organizationID, ledgerID, id string, input *models.UpdateAccountInput) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, organizationID, ledgerID, id, input)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockAccountsServiceMockRecorder) UpdateAccount(ctx, organizationID, ledgerID, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockAccountsService)(nil).UpdateAccount), ctx, organizationID, ledgerID, id, input)
}
