// Code generated by MockGen. DO NOT EDIT.
// Source: asset_rates.go
//
// Generated by this command:
//
//	mockgen -source=asset_rates.go -destination=mocks/mock_asset_rates.go -package=mocks AssetRatesService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v3/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAssetRatesService is a mock of AssetRatesService interface.
type MockAssetRatesService struct {
	ctrl     *gomock.Controller
	recorder *MockAssetRatesServiceMockRecorder
	isgomock struct{}
}

// MockAssetRatesServiceMockRecorder is the mock recorder for MockAssetRatesService.
type MockAssetRatesServiceMockRecorder struct {
	mock *MockAssetRatesService
}

// NewMockAssetRatesService creates a new mock instance.
func NewMockAssetRatesService(ctrl *gomock.Controller) *MockAssetRatesService {
	mock := &MockAssetRatesService{ctrl: ctrl}
	mock.recorder = &MockAssetRatesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetRatesService) EXPECT() *MockAssetRatesServiceMockRecorder {
	return m.recorder
}

// CreateOrUpdateAssetRate mocks base method.
func (m *MockAssetRatesService) CreateOrUpdateAssetRate(ctx context.Context, organizationID, ledgerID string, input *models.CreateAssetRateInput) (*models.AssetRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateAssetRate", ctx, organizationID, ledgerID, input)
	ret0, _ := ret[0].(*models.AssetRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateAssetRate indicates an expected call of CreateOrUpdateAssetRate.
func (mr *MockAssetRatesServiceMockRecorder) CreateOrUpdateAssetRate(ctx, organizationID, ledgerID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateAssetRate", reflect.TypeOf((*MockAssetRatesService)(nil).CreateOrUpdateAssetRate), ctx, organizationID, ledgerID, input)
}

// GetAssetRate mocks base method.
func (m *MockAssetRatesService) GetAssetRate(ctx context.Context, organizationID, ledgerID, externalID string) (*models.AssetRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetRate", ctx, organizationID, ledgerID, externalID)
	ret0, _ := ret[0].(*models.AssetRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetRate indicates an expected call of GetAssetRate.
func (mr *MockAssetRatesServiceMockRecorder) GetAssetRate(ctx, organizationID, ledgerID, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetRate", reflect.TypeOf((*MockAssetRatesService)(nil).GetAssetRate), ctx, organizationID, ledgerID, externalID)
}

// ListAssetRatesByAssetCode mocks base method.
func (m *MockAssetRatesService) ListAssetRatesByAssetCode(ctx context.Context, organizationID, ledgerID, assetCode string, opts models.AssetRatesListOpts) (*models.ListResponse[models.AssetRate], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssetRatesByAssetCode", ctx, organizationID, ledgerID, assetCode, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.AssetRate])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAssetRatesByAssetCode indicates an expected call of ListAssetRatesByAssetCode.
func (mr *MockAssetRatesServiceMockRecorder) ListAssetRatesByAssetCode(ctx, organizationID, ledgerID, assetCode, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssetRatesByAssetCode", reflect.TypeOf((*MockAssetRatesService)(nil).ListAssetRatesByAssetCode), ctx, organizationID, ledgerID, assetCode, opts)
}

// ListAssetRatesByAssetCodeAll mocks base method.
func (m *MockAssetRatesService) ListAssetRatesByAssetCodeAll(ctx context.Context, organizationID, ledgerID, assetCode string, opts models.AssetRatesListOpts) iter.Seq2[models.AssetRate, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssetRatesByAssetCodeAll", ctx, organizationID, ledgerID, assetCode, opts)
	ret0, _ := ret[0].(iter.Seq2[models.AssetRate, error])
	return ret0
}

// ListAssetRatesByAssetCodeAll indicates an expected call of ListAssetRatesByAssetCodeAll.
func (mr *MockAssetRatesServiceMockRecorder) ListAssetRatesByAssetCodeAll(ctx, organizationID, ledgerID, assetCode, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssetRatesByAssetCodeAll", reflect.TypeOf((*MockAssetRatesService)(nil).ListAssetRatesByAssetCodeAll), ctx, organizationID, ledgerID, assetCode, opts)
}

// ListAssetRatesByAssetCodePages mocks base method.
func (m *MockAssetRatesService) ListAssetRatesByAssetCodePages(ctx context.Context, organizationID, ledgerID, assetCode string, opts models.AssetRatesListOpts) iter.Seq2[*models.ListResponse[models.AssetRate], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssetRatesByAssetCodePages", ctx, organizationID, ledgerID, assetCode, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.AssetRate], error])
	return ret0
}

// ListAssetRatesByAssetCodePages indicates an expected call of ListAssetRatesByAssetCodePages.
func (mr *MockAssetRatesServiceMockRecorder) ListAssetRatesByAssetCodePages(ctx, organizationID, ledgerID, assetCode, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssetRatesByAssetCodePages", reflect.TypeOf((*MockAssetRatesService)(nil).ListAssetRatesByAssetCodePages), ctx, organizationID, ledgerID, assetCode, opts)
}
