// Code generated by MockGen. DO NOT EDIT.
// Source: organizations.go
//
// Generated by this command:
//
//	mockgen -source=organizations.go -destination=mocks/mock_organizations.go -package=mocks OrganizationsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v4/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationsService is a mock of OrganizationsService interface.
type MockOrganizationsService struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationsServiceMockRecorder
	isgomock struct{}
}

// MockOrganizationsServiceMockRecorder is the mock recorder for MockOrganizationsService.
type MockOrganizationsServiceMockRecorder struct {
	mock *MockOrganizationsService
}

// NewMockOrganizationsService creates a new mock instance.
func NewMockOrganizationsService(ctrl *gomock.Controller) *MockOrganizationsService {
	mock := &MockOrganizationsService{ctrl: ctrl}
	mock.recorder = &MockOrganizationsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationsService) EXPECT() *MockOrganizationsServiceMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockOrganizationsService) CreateOrganization(ctx context.Context, input *models.CreateOrganizationInput) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, input)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockOrganizationsServiceMockRecorder) CreateOrganization(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockOrganizationsService)(nil).CreateOrganization), ctx, input)
}

// DeleteOrganization mocks base method.
func (m *MockOrganizationsService) DeleteOrganization(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockOrganizationsServiceMockRecorder) DeleteOrganization(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockOrganizationsService)(nil).DeleteOrganization), ctx, id)
}

// GetOrganization mocks base method.
func (m *MockOrganizationsService) GetOrganization(ctx context.Context, id string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", ctx, id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization.
func (mr *MockOrganizationsServiceMockRecorder) GetOrganization(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*MockOrganizationsService)(nil).GetOrganization), ctx, id)
}

// GetOrganizationsMetricsCount mocks base method.
func (m *MockOrganizationsService) GetOrganizationsMetricsCount(ctx context.Context) (*models.MetricsCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationsMetricsCount", ctx)
	ret0, _ := ret[0].(*models.MetricsCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationsMetricsCount indicates an expected call of GetOrganizationsMetricsCount.
func (mr *MockOrganizationsServiceMockRecorder) GetOrganizationsMetricsCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationsMetricsCount", reflect.TypeOf((*MockOrganizationsService)(nil).GetOrganizationsMetricsCount), ctx)
}

// ListOrganizations mocks base method.
func (m *MockOrganizationsService) ListOrganizations(ctx context.Context, opts models.OrganizationsListOpts) (*models.ListResponse[models.Organization], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Organization])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockOrganizationsServiceMockRecorder) ListOrganizations(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockOrganizationsService)(nil).ListOrganizations), ctx, opts)
}

// ListOrganizationsAll mocks base method.
func (m *MockOrganizationsService) ListOrganizationsAll(ctx context.Context, opts models.OrganizationsListOpts) iter.Seq2[models.Organization, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationsAll", ctx, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Organization, error])
	return ret0
}

// ListOrganizationsAll indicates an expected call of ListOrganizationsAll.
func (mr *MockOrganizationsServiceMockRecorder) ListOrganizationsAll(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationsAll", reflect.TypeOf((*MockOrganizationsService)(nil).ListOrganizationsAll), ctx, opts)
}

// ListOrganizationsPages mocks base method.
func (m *MockOrganizationsService) ListOrganizationsPages(ctx context.Context, opts models.OrganizationsListOpts) iter.Seq2[*models.ListResponse[models.Organization], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationsPages", ctx, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Organization], error])
	return ret0
}

// ListOrganizationsPages indicates an expected call of ListOrganizationsPages.
func (mr *MockOrganizationsServiceMockRecorder) ListOrganizationsPages(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationsPages", reflect.TypeOf((*MockOrganizationsService)(nil).ListOrganizationsPages), ctx, opts)
}

// UpdateOrganization mocks base method.
func (m *MockOrganizationsService) UpdateOrganization(ctx context.Context, id string, input *models.UpdateOrganizationInput) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", ctx, id, input)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockOrganizationsServiceMockRecorder) UpdateOrganization(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockOrganizationsService)(nil).UpdateOrganization), ctx, id, input)
}
