// Code generated by MockGen. DO NOT EDIT.
// Source: aliases.go
//
// Generated by this command:
//
//	mockgen -source=aliases.go -destination=mocks/mock_aliases.go -package=mocks AliasesService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v3/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAliasesService is a mock of AliasesService interface.
type MockAliasesService struct {
	ctrl     *gomock.Controller
	recorder *MockAliasesServiceMockRecorder
	isgomock struct{}
}

// MockAliasesServiceMockRecorder is the mock recorder for MockAliasesService.
type MockAliasesServiceMockRecorder struct {
	mock *MockAliasesService
}

// NewMockAliasesService creates a new mock instance.
func NewMockAliasesService(ctrl *gomock.Controller) *MockAliasesService {
	mock := &MockAliasesService{ctrl: ctrl}
	mock.recorder = &MockAliasesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAliasesService) EXPECT() *MockAliasesServiceMockRecorder {
	return m.recorder
}

// CreateAlias mocks base method.
func (m *MockAliasesService) CreateAlias(ctx context.Context, organizationID, holderID string, input *models.CreateAliasInput) (*models.Alias, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlias", ctx, organizationID, holderID, input)
	ret0, _ := ret[0].(*models.Alias)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlias indicates an expected call of CreateAlias.
func (mr *MockAliasesServiceMockRecorder) CreateAlias(ctx, organizationID, holderID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlias", reflect.TypeOf((*MockAliasesService)(nil).CreateAlias), ctx, organizationID, holderID, input)
}

// DeleteAlias mocks base method.
func (m *MockAliasesService) DeleteAlias(ctx context.Context, organizationID, holderID, aliasID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlias", ctx, organizationID, holderID, aliasID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlias indicates an expected call of DeleteAlias.
func (mr *MockAliasesServiceMockRecorder) DeleteAlias(ctx, organizationID, holderID, aliasID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlias", reflect.TypeOf((*MockAliasesService)(nil).DeleteAlias), ctx, organizationID, holderID, aliasID)
}

// DeleteRelatedParty mocks base method.
func (m *MockAliasesService) DeleteRelatedParty(ctx context.Context, organizationID, holderID, aliasID, relatedPartyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRelatedParty", ctx, organizationID, holderID, aliasID, relatedPartyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRelatedParty indicates an expected call of DeleteRelatedParty.
func (mr *MockAliasesServiceMockRecorder) DeleteRelatedParty(ctx, organizationID, holderID, aliasID, relatedPartyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRelatedParty", reflect.TypeOf((*MockAliasesService)(nil).DeleteRelatedParty), ctx, organizationID, holderID, aliasID, relatedPartyID)
}

// GetAlias mocks base method.
func (m *MockAliasesService) GetAlias(ctx context.Context, organizationID, holderID, aliasID string) (*models.Alias, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlias", ctx, organizationID, holderID, aliasID)
	ret0, _ := ret[0].(*models.Alias)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlias indicates an expected call of GetAlias.
func (mr *MockAliasesServiceMockRecorder) GetAlias(ctx, organizationID, holderID, aliasID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlias", reflect.TypeOf((*MockAliasesService)(nil).GetAlias), ctx, organizationID, holderID, aliasID)
}

// ListAliases mocks base method.
func (m *MockAliasesService) ListAliases(ctx context.Context, organizationID string, opts models.AliasesListOpts) (*models.ListResponse[models.Alias], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAliases", ctx, organizationID, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Alias])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAliases indicates an expected call of ListAliases.
func (mr *MockAliasesServiceMockRecorder) ListAliases(ctx, organizationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAliases", reflect.TypeOf((*MockAliasesService)(nil).ListAliases), ctx, organizationID, opts)
}

// ListAliasesAll mocks base method.
func (m *MockAliasesService) ListAliasesAll(ctx context.Context, organizationID string, opts models.AliasesListOpts) iter.Seq2[models.Alias, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAliasesAll", ctx, organizationID, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Alias, error])
	return ret0
}

// ListAliasesAll indicates an expected call of ListAliasesAll.
func (mr *MockAliasesServiceMockRecorder) ListAliasesAll(ctx, organizationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAliasesAll", reflect.TypeOf((*MockAliasesService)(nil).ListAliasesAll), ctx, organizationID, opts)
}

// ListAliasesPages mocks base method.
func (m *MockAliasesService) ListAliasesPages(ctx context.Context, organizationID string, opts models.AliasesListOpts) iter.Seq2[*models.ListResponse[models.Alias], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAliasesPages", ctx, organizationID, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Alias], error])
	return ret0
}

// ListAliasesPages indicates an expected call of ListAliasesPages.
func (mr *MockAliasesServiceMockRecorder) ListAliasesPages(ctx, organizationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAliasesPages", reflect.TypeOf((*MockAliasesService)(nil).ListAliasesPages), ctx, organizationID, opts)
}

// UpdateAlias mocks base method.
func (m *MockAliasesService) UpdateAlias(ctx context.Context, organizationID, holderID, aliasID string, input *models.UpdateAliasInput) (*models.Alias, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlias", ctx, organizationID, holderID, aliasID, input)
	ret0, _ := ret[0].(*models.Alias)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAlias indicates an expected call of UpdateAlias.
func (mr *MockAliasesServiceMockRecorder) UpdateAlias(ctx, organizationID, holderID, aliasID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlias", reflect.TypeOf((*MockAliasesService)(nil).UpdateAlias), ctx, organizationID, holderID, aliasID, input)
}
