// Code generated by MockGen. DO NOT EDIT.
// Source: ledgers.go
//
// Generated by this command:
//
//	mockgen -source=ledgers.go -destination=mocks/mock_ledgers.go -package=mocks LedgersService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v3/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLedgersService is a mock of LedgersService interface.
type MockLedgersService struct {
	ctrl     *gomock.Controller
	recorder *MockLedgersServiceMockRecorder
	isgomock struct{}
}

// MockLedgersServiceMockRecorder is the mock recorder for MockLedgersService.
type MockLedgersServiceMockRecorder struct {
	mock *MockLedgersService
}

// NewMockLedgersService creates a new mock instance.
func NewMockLedgersService(ctrl *gomock.Controller) *MockLedgersService {
	mock := &MockLedgersService{ctrl: ctrl}
	mock.recorder = &MockLedgersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgersService) EXPECT() *MockLedgersServiceMockRecorder {
	return m.recorder
}

// CreateLedger mocks base method.
func (m *MockLedgersService) CreateLedger(ctx context.Context, organizationID string, input *models.CreateLedgerInput) (*models.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLedger", ctx, organizationID, input)
	ret0, _ := ret[0].(*models.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLedger indicates an expected call of CreateLedger.
func (mr *MockLedgersServiceMockRecorder) CreateLedger(ctx, organizationID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLedger", reflect.TypeOf((*MockLedgersService)(nil).CreateLedger), ctx, organizationID, input)
}

// DeleteLedger mocks base method.
func (m *MockLedgersService) DeleteLedger(ctx context.Context, organizationID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLedger", ctx, organizationID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLedger indicates an expected call of DeleteLedger.
func (mr *MockLedgersServiceMockRecorder) DeleteLedger(ctx, organizationID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLedger", reflect.TypeOf((*MockLedgersService)(nil).DeleteLedger), ctx, organizationID, id)
}

// GetLedger mocks base method.
func (m *MockLedgersService) GetLedger(ctx context.Context, organizationID, id string) (*models.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedger", ctx, organizationID, id)
	ret0, _ := ret[0].(*models.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedger indicates an expected call of GetLedger.
func (mr *MockLedgersServiceMockRecorder) GetLedger(ctx, organizationID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedger", reflect.TypeOf((*MockLedgersService)(nil).GetLedger), ctx, organizationID, id)
}

// GetLedgerSettings mocks base method.
func (m *MockLedgersService) GetLedgerSettings(ctx context.Context, organizationID, id string) (*models.LedgerSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgerSettings", ctx, organizationID, id)
	ret0, _ := ret[0].(*models.LedgerSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerSettings indicates an expected call of GetLedgerSettings.
func (mr *MockLedgersServiceMockRecorder) GetLedgerSettings(ctx, organizationID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerSettings", reflect.TypeOf((*MockLedgersService)(nil).GetLedgerSettings), ctx, organizationID, id)
}

// GetLedgersMetricsCount mocks base method.
func (m *MockLedgersService) GetLedgersMetricsCount(ctx context.Context, organizationID string) (*models.MetricsCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgersMetricsCount", ctx, organizationID)
	ret0, _ := ret[0].(*models.MetricsCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgersMetricsCount indicates an expected call of GetLedgersMetricsCount.
func (mr *MockLedgersServiceMockRecorder) GetLedgersMetricsCount(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgersMetricsCount", reflect.TypeOf((*MockLedgersService)(nil).GetLedgersMetricsCount), ctx, organizationID)
}

// ListLedgers mocks base method.
func (m *MockLedgersService) ListLedgers(ctx context.Context, organizationID string, opts models.LedgersListOpts) (*models.ListResponse[models.Ledger], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLedgers", ctx, organizationID, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Ledger])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLedgers indicates an expected call of ListLedgers.
func (mr *MockLedgersServiceMockRecorder) ListLedgers(ctx, organizationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLedgers", reflect.TypeOf((*MockLedgersService)(nil).ListLedgers), ctx, organizationID, opts)
}

// ListLedgersAll mocks base method.
func (m *MockLedgersService) ListLedgersAll(ctx context.Context, organizationID string, opts models.LedgersListOpts) iter.Seq2[models.Ledger, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLedgersAll", ctx, organizationID, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Ledger, error])
	return ret0
}

// ListLedgersAll indicates an expected call of ListLedgersAll.
func (mr *MockLedgersServiceMockRecorder) ListLedgersAll(ctx, organizationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLedgersAll", reflect.TypeOf((*MockLedgersService)(nil).ListLedgersAll), ctx, organizationID, opts)
}

// ListLedgersPages mocks base method.
func (m *MockLedgersService) ListLedgersPages(ctx context.Context, organizationID string, opts models.LedgersListOpts) iter.Seq2[*models.ListResponse[models.Ledger], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLedgersPages", ctx, organizationID, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Ledger], error])
	return ret0
}

// ListLedgersPages indicates an expected call of ListLedgersPages.
func (mr *MockLedgersServiceMockRecorder) ListLedgersPages(ctx, organizationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLedgersPages", reflect.TypeOf((*MockLedgersService)(nil).ListLedgersPages), ctx, organizationID, opts)
}

// UpdateLedger mocks base method.
func (m *MockLedgersService) UpdateLedger(ctx context.Context, organizationID, id string, input *models.UpdateLedgerInput) (*models.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLedger", ctx, organizationID, id, input)
	ret0, _ := ret[0].(*models.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLedger indicates an expected call of UpdateLedger.
func (mr *MockLedgersServiceMockRecorder) UpdateLedger(ctx, organizationID, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLedger", reflect.TypeOf((*MockLedgersService)(nil).UpdateLedger), ctx, organizationID, id, input)
}

// UpdateLedgerSettings mocks base method.
func (m *MockLedgersService) UpdateLedgerSettings(ctx context.Context, organizationID, id string, input *models.UpdateLedgerSettingsInput) (*models.LedgerSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLedgerSettings", ctx, organizationID, id, input)
	ret0, _ := ret[0].(*models.LedgerSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLedgerSettings indicates an expected call of UpdateLedgerSettings.
func (mr *MockLedgersServiceMockRecorder) UpdateLedgerSettings(ctx, organizationID, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLedgerSettings", reflect.TypeOf((*MockLedgersService)(nil).UpdateLedgerSettings), ctx, organizationID, id, input)
}
