// Code generated by MockGen. DO NOT EDIT.
// Source: operations.go
//
// Generated by this command:
//
//	mockgen -source=operations.go -destination=mocks/mock_operations.go -package=mocks OperationsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v3/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOperationsService is a mock of OperationsService interface.
type MockOperationsService struct {
	ctrl     *gomock.Controller
	recorder *MockOperationsServiceMockRecorder
	isgomock struct{}
}

// MockOperationsServiceMockRecorder is the mock recorder for MockOperationsService.
type MockOperationsServiceMockRecorder struct {
	mock *MockOperationsService
}

// NewMockOperationsService creates a new mock instance.
func NewMockOperationsService(ctrl *gomock.Controller) *MockOperationsService {
	mock := &MockOperationsService{ctrl: ctrl}
	mock.recorder = &MockOperationsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationsService) EXPECT() *MockOperationsServiceMockRecorder {
	return m.recorder
}

// GetOperation mocks base method.
func (m *MockOperationsService) GetOperation(ctx context.Context, organizationID, ledgerID, accountID, operationID string) (*models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperation", ctx, organizationID, ledgerID, accountID, operationID)
	ret0, _ := ret[0].(*models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperation indicates an expected call of GetOperation.
func (mr *MockOperationsServiceMockRecorder) GetOperation(ctx, organizationID, ledgerID, accountID, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperation", reflect.TypeOf((*MockOperationsService)(nil).GetOperation), ctx, organizationID, ledgerID, accountID, operationID)
}

// ListOperations mocks base method.
func (m *MockOperationsService) ListOperations(ctx context.Context, organizationID, ledgerID, accountID string, opts models.OperationsListOpts) (*models.ListResponse[models.Operation], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOperations", ctx, organizationID, ledgerID, accountID, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Operation])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOperations indicates an expected call of ListOperations.
func (mr *MockOperationsServiceMockRecorder) ListOperations(ctx, organizationID, ledgerID, accountID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOperations", reflect.TypeOf((*MockOperationsService)(nil).ListOperations), ctx, organizationID, ledgerID, accountID, opts)
}

// ListOperationsAll mocks base method.
func (m *MockOperationsService) ListOperationsAll(ctx context.Context, organizationID, ledgerID, accountID string, opts models.OperationsListOpts) iter.Seq2[models.Operation, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOperationsAll", ctx, organizationID, ledgerID, accountID, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Operation, error])
	return ret0
}

// ListOperationsAll indicates an expected call of ListOperationsAll.
func (mr *MockOperationsServiceMockRecorder) ListOperationsAll(ctx, organizationID, ledgerID, accountID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOperationsAll", reflect.TypeOf((*MockOperationsService)(nil).ListOperationsAll), ctx, organizationID, ledgerID, accountID, opts)
}

// ListOperationsPages mocks base method.
func (m *MockOperationsService) ListOperationsPages(ctx context.Context, organizationID, ledgerID, accountID string, opts models.OperationsListOpts) iter.Seq2[*models.ListResponse[models.Operation], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOperationsPages", ctx, organizationID, ledgerID, accountID, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Operation], error])
	return ret0
}

// ListOperationsPages indicates an expected call of ListOperationsPages.
func (mr *MockOperationsServiceMockRecorder) ListOperationsPages(ctx, organizationID, ledgerID, accountID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOperationsPages", reflect.TypeOf((*MockOperationsService)(nil).ListOperationsPages), ctx, organizationID, ledgerID, accountID, opts)
}

// UpdateTransactionOperation mocks base method.
func (m *MockOperationsService) UpdateTransactionOperation(ctx context.Context, organizationID, ledgerID, transactionID, operationID string, input *models.UpdateOperationInput) (*models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionOperation", ctx, organizationID, ledgerID, transactionID, operationID, input)
	ret0, _ := ret[0].(*models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTransactionOperation indicates an expected call of UpdateTransactionOperation.
func (mr *MockOperationsServiceMockRecorder) UpdateTransactionOperation(ctx, organizationID, ledgerID, transactionID, operationID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionOperation", reflect.TypeOf((*MockOperationsService)(nil).UpdateTransactionOperation), ctx, organizationID, ledgerID, transactionID, operationID, input)
}
