// Code generated by MockGen. DO NOT EDIT.
// Source: assets.go
//
// Generated by this command:
//
//	mockgen -source=assets.go -destination=mocks/mock_assets.go -package=mocks AssetsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v4/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAssetsService is a mock of AssetsService interface.
type MockAssetsService struct {
	ctrl     *gomock.Controller
	recorder *MockAssetsServiceMockRecorder
	isgomock struct{}
}

// MockAssetsServiceMockRecorder is the mock recorder for MockAssetsService.
type MockAssetsServiceMockRecorder struct {
	mock *MockAssetsService
}

// NewMockAssetsService creates a new mock instance.
func NewMockAssetsService(ctrl *gomock.Controller) *MockAssetsService {
	mock := &MockAssetsService{ctrl: ctrl}
	mock.recorder = &MockAssetsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetsService) EXPECT() *MockAssetsServiceMockRecorder {
	return m.recorder
}

// CreateAsset mocks base method.
func (m *MockAssetsService) CreateAsset(ctx context.Context, organizationID, ledgerID string, input *models.CreateAssetInput) (*models.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsset", ctx, organizationID, ledgerID, input)
	ret0, _ := ret[0].(*models.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAsset indicates an expected call of CreateAsset.
func (mr *MockAssetsServiceMockRecorder) CreateAsset(ctx, organizationID, ledgerID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsset", reflect.TypeOf((*MockAssetsService)(nil).CreateAsset), ctx, organizationID, ledgerID, input)
}

// DeleteAsset mocks base method.
func (m *MockAssetsService) DeleteAsset(ctx context.Context, organizationID, ledgerID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAsset", ctx, organizationID, ledgerID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAsset indicates an expected call of DeleteAsset.
func (mr *MockAssetsServiceMockRecorder) DeleteAsset(ctx, organizationID, ledgerID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsset", reflect.TypeOf((*MockAssetsService)(nil).DeleteAsset), ctx, organizationID, ledgerID, id)
}

// GetAsset mocks base method.
func (m *MockAssetsService) GetAsset(ctx context.Context, organizationID, ledgerID, id string) (*models.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAsset", ctx, organizationID, ledgerID, id)
	ret0, _ := ret[0].(*models.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAsset indicates an expected call of GetAsset.
func (mr *MockAssetsServiceMockRecorder) GetAsset(ctx, organizationID, ledgerID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAsset", reflect.TypeOf((*MockAssetsService)(nil).GetAsset), ctx, organizationID, ledgerID, id)
}

// GetAssetsMetricsCount mocks base method.
func (m *MockAssetsService) GetAssetsMetricsCount(ctx context.Context, organizationID, ledgerID string) (*models.MetricsCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetsMetricsCount", ctx, organizationID, ledgerID)
	ret0, _ := ret[0].(*models.MetricsCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetsMetricsCount indicates an expected call of GetAssetsMetricsCount.
func (mr *MockAssetsServiceMockRecorder) GetAssetsMetricsCount(ctx, organizationID, ledgerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetsMetricsCount", reflect.TypeOf((*MockAssetsService)(nil).GetAssetsMetricsCount), ctx, organizationID, ledgerID)
}

// ListAssets mocks base method.
func (m *MockAssetsService) ListAssets(ctx context.Context, organizationID, ledgerID string, opts models.AssetsListOpts) (*models.ListResponse[models.Asset], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssets", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Asset])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAssets indicates an expected call of ListAssets.
func (mr *MockAssetsServiceMockRecorder) ListAssets(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssets", reflect.TypeOf((*MockAssetsService)(nil).ListAssets), ctx, organizationID, ledgerID, opts)
}

// ListAssetsAll mocks base method.
func (m *MockAssetsService) ListAssetsAll(ctx context.Context, organizationID, ledgerID string, opts models.AssetsListOpts) iter.Seq2[models.Asset, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssetsAll", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Asset, error])
	return ret0
}

// ListAssetsAll indicates an expected call of ListAssetsAll.
func (mr *MockAssetsServiceMockRecorder) ListAssetsAll(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssetsAll", reflect.TypeOf((*MockAssetsService)(nil).ListAssetsAll), ctx, organizationID, ledgerID, opts)
}

// ListAssetsPages mocks base method.
func (m *MockAssetsService) ListAssetsPages(ctx context.Context, organizationID, ledgerID string, opts models.AssetsListOpts) iter.Seq2[*models.ListResponse[models.Asset], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssetsPages", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Asset], error])
	return ret0
}

// ListAssetsPages indicates an expected call of ListAssetsPages.
func (mr *MockAssetsServiceMockRecorder) ListAssetsPages(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssetsPages", reflect.TypeOf((*MockAssetsService)(nil).ListAssetsPages), ctx, organizationID, ledgerID, opts)
}

// UpdateAsset mocks base method.
func (m *MockAssetsService) UpdateAsset(ctx context.Context, organizationID, ledgerID, id string, input *models.UpdateAssetInput) (*models.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAsset", ctx, organizationID, ledgerID, id, input)
	ret0, _ := ret[0].(*models.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAsset indicates an expected call of UpdateAsset.
func (mr *MockAssetsServiceMockRecorder) UpdateAsset(ctx, organizationID, ledgerID, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAsset", reflect.TypeOf((*MockAssetsService)(nil).UpdateAsset), ctx, organizationID, ledgerID, id, input)
}
