// Code generated by MockGen. DO NOT EDIT.
// Source: holders.go
//
// Generated by this command:
//
//	mockgen -source=holders.go -destination=mocks/mock_holders.go -package=mocks HoldersService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v4/models"
	gomock "go.uber.org/mock/gomock"
)

// MockHoldersService is a mock of HoldersService interface.
type MockHoldersService struct {
	ctrl     *gomock.Controller
	recorder *MockHoldersServiceMockRecorder
	isgomock struct{}
}

// MockHoldersServiceMockRecorder is the mock recorder for MockHoldersService.
type MockHoldersServiceMockRecorder struct {
	mock *MockHoldersService
}

// NewMockHoldersService creates a new mock instance.
func NewMockHoldersService(ctrl *gomock.Controller) *MockHoldersService {
	mock := &MockHoldersService{ctrl: ctrl}
	mock.recorder = &MockHoldersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHoldersService) EXPECT() *MockHoldersServiceMockRecorder {
	return m.recorder
}

// CreateHolder mocks base method.
func (m *MockHoldersService) CreateHolder(ctx context.Context, organizationID string, input *models.CreateHolderInput) (*models.Holder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHolder", ctx, organizationID, input)
	ret0, _ := ret[0].(*models.Holder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHolder indicates an expected call of CreateHolder.
func (mr *MockHoldersServiceMockRecorder) CreateHolder(ctx, organizationID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHolder", reflect.TypeOf((*MockHoldersService)(nil).CreateHolder), ctx, organizationID, input)
}

// DeleteHolder mocks base method.
func (m *MockHoldersService) DeleteHolder(ctx context.Context, organizationID, holderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHolder", ctx, organizationID, holderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHolder indicates an expected call of DeleteHolder.
func (mr *MockHoldersServiceMockRecorder) DeleteHolder(ctx, organizationID, holderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHolder", reflect.TypeOf((*MockHoldersService)(nil).DeleteHolder), ctx, organizationID, holderID)
}

// GetHolder mocks base method.
func (m *MockHoldersService) GetHolder(ctx context.Context, organizationID, holderID string) (*models.Holder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHolder", ctx, organizationID, holderID)
	ret0, _ := ret[0].(*models.Holder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHolder indicates an expected call of GetHolder.
func (mr *MockHoldersServiceMockRecorder) GetHolder(ctx, organizationID, holderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHolder", reflect.TypeOf((*MockHoldersService)(nil).GetHolder), ctx, organizationID, holderID)
}

// ListHolders mocks base method.
func (m *MockHoldersService) ListHolders(ctx context.Context, organizationID string, opts models.HoldersListOpts) (*models.ListResponse[models.Holder], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHolders", ctx, organizationID, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Holder])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHolders indicates an expected call of ListHolders.
func (mr *MockHoldersServiceMockRecorder) ListHolders(ctx, organizationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHolders", reflect.TypeOf((*MockHoldersService)(nil).ListHolders), ctx, organizationID, opts)
}

// ListHoldersAll mocks base method.
func (m *MockHoldersService) ListHoldersAll(ctx context.Context, organizationID string, opts models.HoldersListOpts) iter.Seq2[models.Holder, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHoldersAll", ctx, organizationID, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Holder, error])
	return ret0
}

// ListHoldersAll indicates an expected call of ListHoldersAll.
func (mr *MockHoldersServiceMockRecorder) ListHoldersAll(ctx, organizationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHoldersAll", reflect.TypeOf((*MockHoldersService)(nil).ListHoldersAll), ctx, organizationID, opts)
}

// ListHoldersPages mocks base method.
func (m *MockHoldersService) ListHoldersPages(ctx context.Context, organizationID string, opts models.HoldersListOpts) iter.Seq2[*models.ListResponse[models.Holder], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHoldersPages", ctx, organizationID, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Holder], error])
	return ret0
}

// ListHoldersPages indicates an expected call of ListHoldersPages.
func (mr *MockHoldersServiceMockRecorder) ListHoldersPages(ctx, organizationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHoldersPages", reflect.TypeOf((*MockHoldersService)(nil).ListHoldersPages), ctx, organizationID, opts)
}

// UpdateHolder mocks base method.
func (m *MockHoldersService) UpdateHolder(ctx context.Context, organizationID, holderID string, input *models.UpdateHolderInput) (*models.Holder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHolder", ctx, organizationID, holderID, input)
	ret0, _ := ret[0].(*models.Holder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHolder indicates an expected call of UpdateHolder.
func (mr *MockHoldersServiceMockRecorder) UpdateHolder(ctx, organizationID, holderID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHolder", reflect.TypeOf((*MockHoldersService)(nil).UpdateHolder), ctx, organizationID, holderID, input)
}
