// Code generated by MockGen. DO NOT EDIT.
// Source: portfolios.go
//
// Generated by this command:
//
//	mockgen -source=portfolios.go -destination=mocks/mock_portfolios.go -package=mocks PortfoliosService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v4/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPortfoliosService is a mock of PortfoliosService interface.
type MockPortfoliosService struct {
	ctrl     *gomock.Controller
	recorder *MockPortfoliosServiceMockRecorder
	isgomock struct{}
}

// MockPortfoliosServiceMockRecorder is the mock recorder for MockPortfoliosService.
type MockPortfoliosServiceMockRecorder struct {
	mock *MockPortfoliosService
}

// NewMockPortfoliosService creates a new mock instance.
func NewMockPortfoliosService(ctrl *gomock.Controller) *MockPortfoliosService {
	mock := &MockPortfoliosService{ctrl: ctrl}
	mock.recorder = &MockPortfoliosServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfoliosService) EXPECT() *MockPortfoliosServiceMockRecorder {
	return m.recorder
}

// CreatePortfolio mocks base method.
func (m *MockPortfoliosService) CreatePortfolio(ctx context.Context, organizationID, ledgerID string, input *models.CreatePortfolioInput) (*models.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePortfolio", ctx, organizationID, ledgerID, input)
	ret0, _ := ret[0].(*models.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePortfolio indicates an expected call of CreatePortfolio.
func (mr *MockPortfoliosServiceMockRecorder) CreatePortfolio(ctx, organizationID, ledgerID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePortfolio", reflect.TypeOf((*MockPortfoliosService)(nil).CreatePortfolio), ctx, organizationID, ledgerID, input)
}

// DeletePortfolio mocks base method.
func (m *MockPortfoliosService) DeletePortfolio(ctx context.Context, organizationID, ledgerID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePortfolio", ctx, organizationID, ledgerID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePortfolio indicates an expected call of DeletePortfolio.
func (mr *MockPortfoliosServiceMockRecorder) DeletePortfolio(ctx, organizationID, ledgerID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePortfolio", reflect.TypeOf((*MockPortfoliosService)(nil).DeletePortfolio), ctx, organizationID, ledgerID, id)
}

// GetPortfolio mocks base method.
func (m *MockPortfoliosService) GetPortfolio(ctx context.Context, organizationID, ledgerID, id string) (*models.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPortfolio", ctx, organizationID, ledgerID, id)
	ret0, _ := ret[0].(*models.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPortfolio indicates an expected call of GetPortfolio.
func (mr *MockPortfoliosServiceMockRecorder) GetPortfolio(ctx, organizationID, ledgerID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPortfolio", reflect.TypeOf((*MockPortfoliosService)(nil).GetPortfolio), ctx, organizationID, ledgerID, id)
}

// GetPortfoliosMetricsCount mocks base method.
func (m *MockPortfoliosService) GetPortfoliosMetricsCount(ctx context.Context, organizationID, ledgerID string) (*models.MetricsCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPortfoliosMetricsCount", ctx, organizationID, ledgerID)
	ret0, _ := ret[0].(*models.MetricsCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPortfoliosMetricsCount indicates an expected call of GetPortfoliosMetricsCount.
func (mr *MockPortfoliosServiceMockRecorder) GetPortfoliosMetricsCount(ctx, organizationID, ledgerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPortfoliosMetricsCount", reflect.TypeOf((*MockPortfoliosService)(nil).GetPortfoliosMetricsCount), ctx, organizationID, ledgerID)
}

// ListPortfolios mocks base method.
func (m *MockPortfoliosService) ListPortfolios(ctx context.Context, organizationID, ledgerID string, opts models.PortfoliosListOpts) (*models.ListResponse[models.Portfolio], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPortfolios", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Portfolio])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPortfolios indicates an expected call of ListPortfolios.
func (mr *MockPortfoliosServiceMockRecorder) ListPortfolios(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPortfolios", reflect.TypeOf((*MockPortfoliosService)(nil).ListPortfolios), ctx, organizationID, ledgerID, opts)
}

// ListPortfoliosAll mocks base method.
func (m *MockPortfoliosService) ListPortfoliosAll(ctx context.Context, organizationID, ledgerID string, opts models.PortfoliosListOpts) iter.Seq2[models.Portfolio, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPortfoliosAll", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Portfolio, error])
	return ret0
}

// ListPortfoliosAll indicates an expected call of ListPortfoliosAll.
func (mr *MockPortfoliosServiceMockRecorder) ListPortfoliosAll(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPortfoliosAll", reflect.TypeOf((*MockPortfoliosService)(nil).ListPortfoliosAll), ctx, organizationID, ledgerID, opts)
}

// ListPortfoliosPages mocks base method.
func (m *MockPortfoliosService) ListPortfoliosPages(ctx context.Context, organizationID, ledgerID string, opts models.PortfoliosListOpts) iter.Seq2[*models.ListResponse[models.Portfolio], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPortfoliosPages", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Portfolio], error])
	return ret0
}

// ListPortfoliosPages indicates an expected call of ListPortfoliosPages.
func (mr *MockPortfoliosServiceMockRecorder) ListPortfoliosPages(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPortfoliosPages", reflect.TypeOf((*MockPortfoliosService)(nil).ListPortfoliosPages), ctx, organizationID, ledgerID, opts)
}

// UpdatePortfolio mocks base method.
func (m *MockPortfoliosService) UpdatePortfolio(ctx context.Context, organizationID, ledgerID, id string, input *models.UpdatePortfolioInput) (*models.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePortfolio", ctx, organizationID, ledgerID, id, input)
	ret0, _ := ret[0].(*models.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePortfolio indicates an expected call of UpdatePortfolio.
func (mr *MockPortfoliosServiceMockRecorder) UpdatePortfolio(ctx, organizationID, ledgerID, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePortfolio", reflect.TypeOf((*MockPortfoliosService)(nil).UpdatePortfolio), ctx, organizationID, ledgerID, id, input)
}
