// Code generated by MockGen. DO NOT EDIT.
// Source: balances.go
//
// Generated by this command:
//
//	mockgen -source=balances.go -destination=mocks/mock_balances.go -package=mocks BalancesService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/LerianStudio/midaz-sdk-golang/v5/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBalancesService is a mock of BalancesService interface.
type MockBalancesService struct {
	ctrl     *gomock.Controller
	recorder *MockBalancesServiceMockRecorder
	isgomock struct{}
}

// MockBalancesServiceMockRecorder is the mock recorder for MockBalancesService.
type MockBalancesServiceMockRecorder struct {
	mock *MockBalancesService
}

// NewMockBalancesService creates a new mock instance.
func NewMockBalancesService(ctrl *gomock.Controller) *MockBalancesService {
	mock := &MockBalancesService{ctrl: ctrl}
	mock.recorder = &MockBalancesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalancesService) EXPECT() *MockBalancesServiceMockRecorder {
	return m.recorder
}

// CreateBalance mocks base method.
func (m *MockBalancesService) CreateBalance(ctx context.Context, organizationID, ledgerID, accountID string, input *models.CreateBalanceInput) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBalance", ctx, organizationID, ledgerID, accountID, input)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBalance indicates an expected call of CreateBalance.
func (mr *MockBalancesServiceMockRecorder) CreateBalance(ctx, organizationID, ledgerID, accountID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBalance", reflect.TypeOf((*MockBalancesService)(nil).CreateBalance), ctx, organizationID, ledgerID, accountID, input)
}

// DeleteBalance mocks base method.
func (m *MockBalancesService) DeleteBalance(ctx context.Context, organizationID, ledgerID, balanceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBalance", ctx, organizationID, ledgerID, balanceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBalance indicates an expected call of DeleteBalance.
func (mr *MockBalancesServiceMockRecorder) DeleteBalance(ctx, organizationID, ledgerID, balanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBalance", reflect.TypeOf((*MockBalancesService)(nil).DeleteBalance), ctx, organizationID, ledgerID, balanceID)
}

// GetAccountBalancesHistory mocks base method.
func (m *MockBalancesService) GetAccountBalancesHistory(ctx context.Context, organizationID, ledgerID, accountID, date string) ([]models.BalanceHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalancesHistory", ctx, organizationID, ledgerID, accountID, date)
	ret0, _ := ret[0].([]models.BalanceHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalancesHistory indicates an expected call of GetAccountBalancesHistory.
func (mr *MockBalancesServiceMockRecorder) GetAccountBalancesHistory(ctx, organizationID, ledgerID, accountID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalancesHistory", reflect.TypeOf((*MockBalancesService)(nil).GetAccountBalancesHistory), ctx, organizationID, ledgerID, accountID, date)
}

// GetBalance mocks base method.
func (m *MockBalancesService) GetBalance(ctx context.Context, organizationID, ledgerID, balanceID string) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, organizationID, ledgerID, balanceID)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBalancesServiceMockRecorder) GetBalance(ctx, organizationID, ledgerID, balanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBalancesService)(nil).GetBalance), ctx, organizationID, ledgerID, balanceID)
}

// GetBalanceHistory mocks base method.
func (m *MockBalancesService) GetBalanceHistory(ctx context.Context, organizationID, ledgerID, balanceID, date string) (*models.BalanceHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceHistory", ctx, organizationID, ledgerID, balanceID, date)
	ret0, _ := ret[0].(*models.BalanceHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceHistory indicates an expected call of GetBalanceHistory.
func (mr *MockBalancesServiceMockRecorder) GetBalanceHistory(ctx, organizationID, ledgerID, balanceID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceHistory", reflect.TypeOf((*MockBalancesService)(nil).GetBalanceHistory), ctx, organizationID, ledgerID, balanceID, date)
}

// ListAccountBalances mocks base method.
func (m *MockBalancesService) ListAccountBalances(ctx context.Context, organizationID, ledgerID, accountID string, opts models.BalancesListOpts) (*models.ListResponse[models.Balance], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountBalances", ctx, organizationID, ledgerID, accountID, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Balance])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountBalances indicates an expected call of ListAccountBalances.
func (mr *MockBalancesServiceMockRecorder) ListAccountBalances(ctx, organizationID, ledgerID, accountID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountBalances", reflect.TypeOf((*MockBalancesService)(nil).ListAccountBalances), ctx, organizationID, ledgerID, accountID, opts)
}

// ListAccountBalancesAll mocks base method.
func (m *MockBalancesService) ListAccountBalancesAll(ctx context.Context, organizationID, ledgerID, accountID string, opts models.BalancesListOpts) iter.Seq2[models.Balance, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountBalancesAll", ctx, organizationID, ledgerID, accountID, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Balance, error])
	return ret0
}

// ListAccountBalancesAll indicates an expected call of ListAccountBalancesAll.
func (mr *MockBalancesServiceMockRecorder) ListAccountBalancesAll(ctx, organizationID, ledgerID, accountID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountBalancesAll", reflect.TypeOf((*MockBalancesService)(nil).ListAccountBalancesAll), ctx, organizationID, ledgerID, accountID, opts)
}

// ListAccountBalancesPages mocks base method.
func (m *MockBalancesService) ListAccountBalancesPages(ctx context.Context, organizationID, ledgerID, accountID string, opts models.BalancesListOpts) iter.Seq2[*models.ListResponse[models.Balance], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountBalancesPages", ctx, organizationID, ledgerID, accountID, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Balance], error])
	return ret0
}

// ListAccountBalancesPages indicates an expected call of ListAccountBalancesPages.
func (mr *MockBalancesServiceMockRecorder) ListAccountBalancesPages(ctx, organizationID, ledgerID, accountID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountBalancesPages", reflect.TypeOf((*MockBalancesService)(nil).ListAccountBalancesPages), ctx, organizationID, ledgerID, accountID, opts)
}

// ListBalances mocks base method.
func (m *MockBalancesService) ListBalances(ctx context.Context, organizationID, ledgerID string, opts models.BalancesListOpts) (*models.ListResponse[models.Balance], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalances", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Balance])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBalances indicates an expected call of ListBalances.
func (mr *MockBalancesServiceMockRecorder) ListBalances(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalances", reflect.TypeOf((*MockBalancesService)(nil).ListBalances), ctx, organizationID, ledgerID, opts)
}

// ListBalancesAll mocks base method.
func (m *MockBalancesService) ListBalancesAll(ctx context.Context, organizationID, ledgerID string, opts models.BalancesListOpts) iter.Seq2[models.Balance, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalancesAll", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Balance, error])
	return ret0
}

// ListBalancesAll indicates an expected call of ListBalancesAll.
func (mr *MockBalancesServiceMockRecorder) ListBalancesAll(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalancesAll", reflect.TypeOf((*MockBalancesService)(nil).ListBalancesAll), ctx, organizationID, ledgerID, opts)
}

// ListBalancesByAccountAlias mocks base method.
func (m *MockBalancesService) ListBalancesByAccountAlias(ctx context.Context, organizationID, ledgerID, alias string, opts models.BalancesListOpts) (*models.ListResponse[models.Balance], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalancesByAccountAlias", ctx, organizationID, ledgerID, alias, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Balance])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBalancesByAccountAlias indicates an expected call of ListBalancesByAccountAlias.
func (mr *MockBalancesServiceMockRecorder) ListBalancesByAccountAlias(ctx, organizationID, ledgerID, alias, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalancesByAccountAlias", reflect.TypeOf((*MockBalancesService)(nil).ListBalancesByAccountAlias), ctx, organizationID, ledgerID, alias, opts)
}

// ListBalancesByAccountAliasAll mocks base method.
func (m *MockBalancesService) ListBalancesByAccountAliasAll(ctx context.Context, organizationID, ledgerID, alias string, opts models.BalancesListOpts) iter.Seq2[models.Balance, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalancesByAccountAliasAll", ctx, organizationID, ledgerID, alias, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Balance, error])
	return ret0
}

// ListBalancesByAccountAliasAll indicates an expected call of ListBalancesByAccountAliasAll.
func (mr *MockBalancesServiceMockRecorder) ListBalancesByAccountAliasAll(ctx, organizationID, ledgerID, alias, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalancesByAccountAliasAll", reflect.TypeOf((*MockBalancesService)(nil).ListBalancesByAccountAliasAll), ctx, organizationID, ledgerID, alias, opts)
}

// ListBalancesByAccountAliasPages mocks base method.
func (m *MockBalancesService) ListBalancesByAccountAliasPages(ctx context.Context, organizationID, ledgerID, alias string, opts models.BalancesListOpts) iter.Seq2[*models.ListResponse[models.Balance], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalancesByAccountAliasPages", ctx, organizationID, ledgerID, alias, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Balance], error])
	return ret0
}

// ListBalancesByAccountAliasPages indicates an expected call of ListBalancesByAccountAliasPages.
func (mr *MockBalancesServiceMockRecorder) ListBalancesByAccountAliasPages(ctx, organizationID, ledgerID, alias, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalancesByAccountAliasPages", reflect.TypeOf((*MockBalancesService)(nil).ListBalancesByAccountAliasPages), ctx, organizationID, ledgerID, alias, opts)
}

// ListBalancesByExternalCode mocks base method.
func (m *MockBalancesService) ListBalancesByExternalCode(ctx context.Context, organizationID, ledgerID, code string, opts models.BalancesListOpts) (*models.ListResponse[models.Balance], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalancesByExternalCode", ctx, organizationID, ledgerID, code, opts)
	ret0, _ := ret[0].(*models.ListResponse[models.Balance])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBalancesByExternalCode indicates an expected call of ListBalancesByExternalCode.
func (mr *MockBalancesServiceMockRecorder) ListBalancesByExternalCode(ctx, organizationID, ledgerID, code, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalancesByExternalCode", reflect.TypeOf((*MockBalancesService)(nil).ListBalancesByExternalCode), ctx, organizationID, ledgerID, code, opts)
}

// ListBalancesByExternalCodeAll mocks base method.
func (m *MockBalancesService) ListBalancesByExternalCodeAll(ctx context.Context, organizationID, ledgerID, code string, opts models.BalancesListOpts) iter.Seq2[models.Balance, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalancesByExternalCodeAll", ctx, organizationID, ledgerID, code, opts)
	ret0, _ := ret[0].(iter.Seq2[models.Balance, error])
	return ret0
}

// ListBalancesByExternalCodeAll indicates an expected call of ListBalancesByExternalCodeAll.
func (mr *MockBalancesServiceMockRecorder) ListBalancesByExternalCodeAll(ctx, organizationID, ledgerID, code, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalancesByExternalCodeAll", reflect.TypeOf((*MockBalancesService)(nil).ListBalancesByExternalCodeAll), ctx, organizationID, ledgerID, code, opts)
}

// ListBalancesByExternalCodePages mocks base method.
func (m *MockBalancesService) ListBalancesByExternalCodePages(ctx context.Context, organizationID, ledgerID, code string, opts models.BalancesListOpts) iter.Seq2[*models.ListResponse[models.Balance], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalancesByExternalCodePages", ctx, organizationID, ledgerID, code, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Balance], error])
	return ret0
}

// ListBalancesByExternalCodePages indicates an expected call of ListBalancesByExternalCodePages.
func (mr *MockBalancesServiceMockRecorder) ListBalancesByExternalCodePages(ctx, organizationID, ledgerID, code, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalancesByExternalCodePages", reflect.TypeOf((*MockBalancesService)(nil).ListBalancesByExternalCodePages), ctx, organizationID, ledgerID, code, opts)
}

// ListBalancesPages mocks base method.
func (m *MockBalancesService) ListBalancesPages(ctx context.Context, organizationID, ledgerID string, opts models.BalancesListOpts) iter.Seq2[*models.ListResponse[models.Balance], error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalancesPages", ctx, organizationID, ledgerID, opts)
	ret0, _ := ret[0].(iter.Seq2[*models.ListResponse[models.Balance], error])
	return ret0
}

// ListBalancesPages indicates an expected call of ListBalancesPages.
func (mr *MockBalancesServiceMockRecorder) ListBalancesPages(ctx, organizationID, ledgerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalancesPages", reflect.TypeOf((*MockBalancesService)(nil).ListBalancesPages), ctx, organizationID, ledgerID, opts)
}

// UpdateBalance mocks base method.
func (m *MockBalancesService) UpdateBalance(ctx context.Context, organizationID, ledgerID, balanceID string, input *models.UpdateBalanceInput) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, organizationID, ledgerID, balanceID, input)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockBalancesServiceMockRecorder) UpdateBalance(ctx, organizationID, ledgerID, balanceID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockBalancesService)(nil).UpdateBalance), ctx, organizationID, ledgerID, balanceID, input)
}
