name: "Enforce Branch PR's from Develop"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  check-branch:
    runs-on: ubuntu-24.04
    steps:
      - name: Check if PR is from develop or hotfix
        if: github.event.pull_request.head.ref != 'develop' && startsWith(github.event.pull_request.head.ref, 'hotfix/') == false
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          echo "Pull requests to main can only come from develop or hotfix branches."
          # Add a request for changes comment on the pull request
          curl --fail-with-body --show-error --silent -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"body": "Pull requests to **main** can only come from **develop** or **hotfix** branches. Please **change base**!!!", "event": "REQUEST_CHANGES"}' \
            "${{ github.event.pull_request.url }}/reviews"
          exit 1
