name: Midaz Go SDK Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  release:
    name: Release with GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Run tests
        run: make test

      - name: Generate test coverage
        run: make coverage

      - name: Generate documentation
        run: make godoc-static

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: artifacts/coverage.html